config/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # path('admin/', admin.site.urls),
    # path('', include('main.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]
urlpatterns += i18n_patterns(
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
    path('', include('main.urls'))
)
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path, include

from .views import *

urlpatterns = [
    path('', home, name='home'),
    path('enrollee/', enrollee, name='enrollee'),
    path('quotas/', quotas, name='quotas'),
    path('finans/', finans, name='finans'),
    path('international_relationships/', international_relationships, name='international_relationships'),
    path('programs/', programs, name='programs'),
    path('ads/', ads, name='ads'),
    path('ads/category/<int:pk>', ads_category, name='ads_category'),
    path('ad/<int:pk>', ad, name="ad"),
    path('news/', news, name='news'),
    path('science/', science, name='science'),
    path('decree/', decree, name='decree'),
    path('magistr/', magistr, name='magistr'),
    path('regulations/', regulations, name='regulations'),
    path('news/category/<int:pk>', news_category, name='news_category'),
    path('new/<int:pk>', new, name="new"),
    path('central_department/', central_department, name="central_department"),
    path('facultets/', facultets, name="facultets"),
    path('fotos/', fotos, name="fotos"),
    path('foto/event/<int:pk>', foto, name='foto'),
    path('department/', department, name="department"),
    path('management/', management, name="management"),
    path('spirtual_education/', spirtual_education, name="spirtual_education"),
    path('external_department/', external_department, name="external_department"),
]

main/models.py
from django.db import models
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField


class Enrollee(models.Model):
    title = models.CharField(max_length=255, verbose_name="Заголовок")
    image = models.ImageField(upload_to='pages/', verbose_name="Излбражение")
    description = RichTextUploadingField(verbose_name="Текст")

    class Meta:
        verbose_name = 'данные об абитуриентах'
        verbose_name_plural = 'Абитуриенты'

    def __str__(self):
        return self.title


class Questions(models.Model):
    questions = models.ForeignKey(Enrollee, on_delete=models.CASCADE, verbose_name="абитуриет")
    question = models.CharField(max_length=500, verbose_name="Вопрос")
    answer = RichTextUploadingField(verbose_name="Ответ")

    class Meta:
        verbose_name = 'часто задаваемый вопрос'
        verbose_name_plural = 'Часто задаваемые вопросы'


class Quotas(models.Model):
    title = models.CharField(max_length=255, verbose_name="Заголовок")
    table = RichTextUploadingField(verbose_name="Таблица")

    class Meta:
        verbose_name = 'данные о квотах'
        verbose_name_plural = 'Квоты'


class Finans(models.Model):
    title = models.CharField(max_length=255, verbose_name="Заголовок")
    table = RichTextUploadingField(verbose_name="Таблица")

    class Meta:
        verbose_name = 'данные о финансовой деятельности'
        verbose_name_plural = 'Финансовая деятельность'


class Programs(models.Model):
    title = models.CharField(max_length=255, verbose_name="Заголовок")
    image = models.ImageField(upload_to='pages/')
    content = RichTextUploadingField(verbose_name="Текст")
    scheme = RichTextUploadingField(verbose_name="Схемы")
    table = RichTextUploadingField(verbose_name="Таблица")

    class Meta:
        verbose_name = 'данные о программах'
        verbose_name_plural = 'Программы'


class AdsCategory(models.Model):
    name = models.CharField(max_length=255, verbose_name="Название")
    description = models.CharField(max_length=255, verbose_name="Описание")

    class Meta:
        verbose_name = 'категории объявлений'
        verbose_name_plural = 'Категории объявлений'

    def __str__(self):
        return self.name


class Ad(models.Model):
    ad = models.ForeignKey(AdsCategory, on_delete=models.CASCADE, verbose_name="Категория объявлений")
    image = models.ImageField(upload_to='pages/', null=True, blank=True, verbose_name="Излбражение")
    title = models.CharField(max_length=255, verbose_name="Заголовок")
    description = models.CharField(max_length=255, verbose_name="Описание")
    content = RichTextUploadingField(verbose_name="Текст")

    class Meta:
        verbose_name = 'объявление'
        verbose_name_plural = 'Объявления'


class NewsCategory(models.Model):
    name = models.CharField(max_length=255, verbose_name="Название")
    description = models.CharField(max_length=255, verbose_name="Описание")

    class Meta:
        verbose_name = 'категории новостей'
        verbose_name_plural = 'Категории новостей'

    def __str__(self):
        return self.name


class New(models.Model):
    new = models.ForeignKey(NewsCategory, on_delete=models.CASCADE, verbose_name="Категория новости")
    image = models.ImageField(upload_to='pages/', null=True, blank=True, verbose_name="Излбражение")
    title = models.CharField(max_length=255, verbose_name="Заголовок")
    description = models.CharField(max_length=255, verbose_name="Описание")
    content = RichTextUploadingField(verbose_name="Текст")

    class Meta:
        verbose_name = 'новость'
        verbose_name_plural = 'Новости'


class CentralDepartments(models.Model):
    icon = models.ImageField(upload_to='pages/')
    name = models.CharField(max_length=255, verbose_name="Название")
    image = models.ImageField(upload_to='pages/', verbose_name="Излбражение")
    boss = models.CharField(max_length=255, verbose_name="Глава отдела")
    time = models.CharField(max_length=255, null=True, blank=True, verbose_name="Время приема")
    phone = models.CharField(max_length=255, verbose_name="Номер телефона")
    email = models.CharField(max_length=255, verbose_name="адрес электронной почты")
    web = models.CharField(max_length=255, verbose_name="Сайт")
    location = models.CharField(max_length=255, verbose_name="место")
    content = RichTextUploadingField(verbose_name="Текст")

    class Meta:
        verbose_name = 'данные о центральных отделах'
        verbose_name_plural = 'Центральные отделы'


class InternationalRelationships(models.Model):
    icon = models.ImageField(upload_to='pages/', verbose_name="иконка")
    name = models.CharField(max_length=255, verbose_name="Название")
    content = RichTextUploadingField(verbose_name="Текст")

    class Meta:
        verbose_name = 'данные о международных отножений'
        verbose_name_plural = 'Международные отношения'


class Departments(models.Model):
    icon = models.ImageField(upload_to='pages/', verbose_name="иконка")
    name = models.CharField(max_length=255, verbose_name="Название")
    image = models.ImageField(upload_to='pages/', verbose_name="Излбражение")
    boss = models.CharField(max_length=255, verbose_name="Глава кафедры")
    time = models.CharField(max_length=255, verbose_name="Время приема")
    phone = models.CharField(max_length=255, verbose_name="Номер телефона")
    email = models.CharField(max_length=255, verbose_name="адрес электронной почты")
    location = models.CharField(max_length=255, verbose_name="место")
    content = RichTextUploadingField(verbose_name="История")
    more = RichTextUploadingField(null=True, blank=True, verbose_name="Больше информации")

    class Meta:
        verbose_name = 'Кафедра ДТПИ'
        verbose_name_plural = 'Кафедры ДТПИ'


class Management(models.Model):
    position = models.CharField(max_length=255, verbose_name="Дослжность")
    image = models.ImageField(upload_to='pages/', verbose_name="Излбражение")
    full_name = models.CharField(max_length=255, verbose_name="Ф. И. О.")
    time = models.CharField(max_length=255, verbose_name="Время приема")
    phone = models.CharField(max_length=255, verbose_name="Номер телефона")
    email = models.CharField(max_length=255, verbose_name="Aдрес электронной почты")
    work_activities = RichTextUploadingField(verbose_name="Трудовая деятельность")

    class Meta:
        verbose_name = 'члена руководства'
        verbose_name_plural = 'Рукаводство'


class ExternalDepartment(models.Model):
    position = models.CharField(max_length=255, verbose_name="Дослжность")
    image = models.ImageField(upload_to='pages/', verbose_name="Излбражение")
    full_name = models.CharField(max_length=255, verbose_name="Ф. И. О.")
    time = models.CharField(max_length=255, verbose_name="Время приема")
    phone = models.CharField(max_length=255, verbose_name="Номер телефона")
    email = models.CharField(max_length=255, verbose_name="адрес электронной почты")
    location = models.CharField(max_length=255, verbose_name="место")

    class Meta:
        verbose_name = 'данные о заочном отделении'
        verbose_name_plural = 'Заочное отделение'


class SpirtualEducation(models.Model):
    title = models.CharField(max_length=255, verbose_name="Заголовок")
    image = models.ImageField(upload_to='pages/', verbose_name="Излбражение")
    content = RichTextUploadingField(verbose_name="Текст")

    class Meta:
        verbose_name = 'данные о духовном образовании'
        verbose_name_plural = 'Духовное образование'


class FotoCategory(models.Model):
    title = models.CharField(max_length=255, verbose_name="Событие")
    descr = models.TextField(null=True, blank=True, verbose_name="Описание")

    class Meta:
        verbose_name = 'категорию фотогалереи'
        verbose_name_plural = 'Категории фотогалереи'

    def __str__(self):
        return self.title


class Foto(models.Model):
    foto = models.ForeignKey(FotoCategory, on_delete=models.CASCADE, verbose_name="Категории фото", null=True,
                             blank=True)
    about = models.CharField(max_length=255, null=True, blank=True, verbose_name="(Описание) На фото ... ")
    image = models.ImageField(upload_to='foto/', verbose_name="Излбражение")

    class Meta:
        verbose_name = 'фотографию'
        verbose_name_plural = 'Фотографии'


class Facultets(models.Model):
    icon = models.ImageField(upload_to='pages/', verbose_name="Главная фотка")
    name = models.CharField(max_length=255, verbose_name="Название")
    image = models.ImageField(upload_to='pages/', verbose_name="Излбражение")
    boss = models.CharField(max_length=255, verbose_name="Глава Факультета")
    time = models.CharField(max_length=255, null=True, blank=True, verbose_name="Время приема")
    phone = models.CharField(max_length=255, verbose_name="Номер телефона")
    email = models.CharField(max_length=255, verbose_name="адрес электронной почты")
    location = models.CharField(max_length=255, verbose_name="место")
    content = RichTextUploadingField(verbose_name="Текст")
    more = RichTextUploadingField(null=True, blank=True, verbose_name="Больше информации")

    class Meta:
        verbose_name = 'факультет'
        verbose_name_plural = 'Факультеты'

    def __str__(self):
        return self.name


class FacultetAdmins(models.Model):
    facultetAdmins = models.ForeignKey(Facultets, on_delete=models.CASCADE, verbose_name="Факультет")
    position = models.CharField(max_length=255, verbose_name="Дослжность")
    image = models.ImageField(upload_to='facultet-admins/', verbose_name="Излбражение")
    fullname = models.CharField(max_length=255, verbose_name="Ф. И. О.")
    time = models.CharField(max_length=255, null=True, blank=True, verbose_name="Время приема")
    phone = models.CharField(max_length=255, verbose_name="Номер телефона")
    email = models.CharField(max_length=255, verbose_name="адрес электронной почты")

templates/ad.html
{% extends 'base.html' %} {% load static %} {% load i18n %}
{% block title %} {{ c.title }} {% endblock %}
{% block content %}



    <section class="section-adz">
        <section class="section-content">
            <div class="container-xl">
                <div class="text-center">
                    <img src="{{c.image.url}}" class="img-fluid img w-100" alt="">
                </div>

                <a href="{% url 'ads_category' c.ad_id %}" style="font-size: 20px; color: #444444" class="text-left">{{ c.ad }}</a>
                <h2 class="title text-left">
                    {{ c.title }}
                </h2>

                <p class="content">
                    {{ c.content | safe }}
                </p>


                <div class="text-center py-5 my-4">
                    <a href="{% url 'ads' %}" class="btn">{% translate "К объявлениям" %}</a>
                </div>


                <div class="row row-cols-1 row-cols-lg-3 ads">
                    {% for ad in category.ad_set.all|slice:":3" %}
                        <div class="col ad">
                            <img src="{{ ad.image.url }}" class="img-fluid w-100" alt="">
                            <div class="title">{{ ad.title }}</div>
                            <div class="descrip">{{ ad.description }}</div>
                            <a href="{% url 'ad' ad.pk %}" class="link">{% translate "Подробнее об объявлении >" %}</a>
                        </div>
                    {% endfor %}
                </div>


            </div>
        </section>
    </section>




{% endblock %}

templates/decree.html
{% extends 'base.html' %} {% load static %} {% load i18n %}
{% block title %} Markaz Bo'limlari {% endblock %}
{% block content %}

    <section class="section-decree" id="top">
        <section class="section-sections">
            <div class="container-xl">
                <h2 class="text-center title">{% translate "Qarorlar" %}</h2>
                <div class="descr">
                    {% translate "Ознакомьтесь с уставными документами нашего института" %}
                </div>

                <div class="content">

                    <nav>
                        <div class="nav nav-tabs sections " id="nav-tab" role="tablist">
                            {% for c in content %}

                                <a class="nav-link " target="_blank" href="{{ c.file.url }}">

                                    <div class="box d-flex align-items-center">
                                        <img src="{{ c.icon.url }}" class="img-fluid pr-5" alt="">
                                        <div class="title ">
                                            {{ c.title }}
                                        </div>
                                    </div>

                                </a>
                            {% endfor %}
                        </div>
                    </nav>
                    <div class="text-center">
                        <a href="{% url 'home' %}" class="btn">{% translate "На главную" %}</a>
                    </div>

                </div>
            </div>
        </section>
    </section>


{% endblock %}

templates/driver.html
{% extends 'base.html' %} {% load static %}{% load i18n %}
{% block title %} E`LONLAR {% endblock %}
{% block content %}


    <section class="section-ads">
        <section class="section-content">
            <div class="container-xl">

фывфывфы
            </div>
        </section>
    </section>

{% endblock %}

templates/enrollee.html
{% extends 'base.html' %} {% load static %}{% load i18n %}
{% block title %} YO'RIQNOMA {% endblock %}
{% block content %}


    {% for content in content %}
        <section class="section-prestudent">
            <section class="section-guide">
                <div class="container-xl">
                    <h2 class="text-center title">
                        {{ content.title }}
                    </h2>

                    <img src="{{ content.image.url }}" class="img-fluid w-100" alt="">

                    <div class="content">
                        <div class="txt">
                            {{ content.description | safe }}
                        </div>
                        <img src="" class="img-fluid" alt="">

                        <div class="questions">
                            {% for question in content.questions_set.all %}
                                <div class="question">
                                    <a class="w-100 click" data-toggle="collapse" href="#collapse{{ question.id }}" role="button"
                                       aria-expanded="false" aria-controls="collapseExample">
                                        <div class="row">
                                            <div class="col-10 text-left qq">
                                                {{ question.question }}
                                            </div>
                                            <div class="col-2 text-right">
                                                <img src="{% static 'img/Arrow-collapse.png' %}"
                                                     class="img-fluid arrow-up"
                                                     alt="">
                                            </div>
                                        </div>
                                    </a>

                                    <div class="collapse" id="collapse{{ question.id }}">
                                        <div class=" res">
                                            <div class="txt">
                                                {{ question.answer | safe }}
                                            </div>
                                            <div class="closee" data-toggle="collapse" href="#collapse{{ question.id }}"
                                                 role="button"
                                                 aria-expanded="false" aria-controls="collapseExample">
                                                 {% translate "Свернуть" %} <img src="{% static 'img/arrow_up.png' %}"
                                                              class="img-fluid pl-3"
                                                              alt="">
                                            </div>
                                        </div>


                                    </div>
                                </div>
                            {% endfor %}
                        </div>

                    </div>
                </div>
            </section>
        </section>
    {% endfor %}


{% endblock %}

templates/facultets.html
{% extends 'base.html' %} {% load static %}{% load i18n %}
{% block title %} Markaz Bo'limlari {% endblock %}
{% block content %}

    <section class="section-facultet-page" id="top">
        <section class="section-facultet">
            <div class="container-xl">
                <h2 class="text-center title">{% translate "ФАКУЛЬТЕТЫ" %}</h2>
                <div class="descr">
                    {% translate "Bizda faoliyat yuritayotgan fakultetlar haqida malumotlar olishingiz va ularning faoliyati bilan
                    tanishishigiz mumkin bizning xodimlar doimo sizni qo’llab-quvatlaydi." %}
                </div>

                <div class="content">

                    <nav>
                        <div class="nav nav-tabs row row-cols-2 row-cols-lg-3 facultet " id="nav-tab" role="tablist">
                            {% for c in content %}

                                <a class="nav-link "
                                   onclick="document.querySelector('.section-facultet-content').classList.remove('d-none');setTimeout(() => {document.getElementById('nav-tabContent').scrollIntoView();}, 100); "
                                   id="nav-{{ c.id }}-tab" data-toggle="tab" href="#nav-{{ c.id }}" role="tab"
                                   aria-controls="nav-{{ c.id }}" aria-selected="true">

                                    <div class="box d-flex flex-column justify-content-between align-items-center">
                                        <img src="{{ c.icon.url }}" class="img-fluid " alt="">
                                        <div class="title ">
                                            {{ c.name }}
                                        </div>
                                    </div>

                                </a>
                            {% endfor %}
                        </div>
                    </nav>

                    <div class="text-center">
                        <a href="{% url 'home' %}" class="btn">{% translate "На главную" %}</a>
                    </div>
                </div>
            </div>
        </section>

        <section class="section-facultet-content d-none">
            <div class="container-xl">
                <div class="tab-content facultet-content" id="nav-tabContent">
                    {% for c in content %}

                        <div class="tab-pane fade " id="nav-{{ c.id }}" role="tabpanel"
                             aria-labelledby="nav-{{ c.id }}-tab">
                            <h2 class="title text-center">
                                {{ c.name }}
                            </h2>

                            <div class="row boss">
                                <div class="col-4">
                                    <div class="image ">
                                        <img src="{{ c.image.url }}" class="img-fluid w-75" alt="">
                                    </div>
                                </div>
                                <div class="col-lg-8 infos">
                                    <div class="info"><span>{% translate "DEKAN:" %}</span> {{ c.boss }}</div>
                                    <div class="info"><span>{% translate "Qabul vaqti:" %}</span> {{ c.time }}</div>
                                    <div class="info"><span>{% translate "Telefon:" %}</span> {{ c.phone }}</div>
                                    <div class="info"><span>{% translate "E-mail:" %}</span> {{ c.email }}</div>
                                    <div class="info"><span>{% translate "Manzil:" %}</span> {{ c.location }}</div>
                                </div>
                            </div>

                            <div class="txt">
                                {{ c.content |safe }}

                                {% if c.more %}
                                    <div class="questions my-5">
                                        <div class="question">
                                            <a class="w-100 click" data-toggle="collapse"
                                               href="#collapse{{ c.id }}" role="button"
                                               aria-expanded="false" aria-controls="collapseExample">
                                                <div class="row">
                                                    <div class="col-10 text-left qq">
                                                        {% translate "Больше информации о факультете" %}
                                                    </div>
                                                    <div class="col-2 text-right">
                                                        <img src="{% static 'img/arrow-fa.png' %}"
                                                             class="img-fluid arrow-up"
                                                             alt="">
                                                    </div>
                                                </div>
                                            </a>

                                            <div class="collapse" id="collapse{{ c.id }}">
                                                <div class=" res">
                                                    <div class="txt">
                                                        {{ c.more | safe }}
                                                    </div>
                                                    <div class="closee" data-toggle="collapse"
                                                         href="#collapse{{ c.id }}"
                                                         role="button"
                                                         aria-expanded="false" aria-controls="collapseExample">
                                                         {% translate "Свернуть" %} <img src="{% static 'img/arrow-upp.png' %}"
                                                                      class="img-fluid pl-3"
                                                                      alt="">
                                                    </div>
                                                </div>


                                            </div>
                                        </div>
                                    </div>
                                {% endif %}

                                {% if c.facultetadmins_set.all|length > 0 %}

                                    <h2 class="my-5">{% translate "Администрация факультета:" %}</h2>

                                    {% for cc in c.facultetadmins_set.all %}

                                        <div class="row staff">
                                            <div class="col-4">
                                                <div class="image ">
                                                    <img src="{{ cc.image.url }}" class="img-fluid w-75" alt="">
                                                </div>
                                            </div>
                                            <div class="col-lg-8 infos">
                                                <div class="info"><span>{{ cc.position }} :</span> {{ cc.fullname }}
                                                </div>
                                                <div class="info"><span>{% translate "Qabul vaqti:" %}</span> {{ cc.time }}</div>
                                                <div class="info"><span>{% translate "Telefon:" %}</span> {{ cc.phone }}</div>
                                                <div class="info"><span>{% translate "E-mail:" %}</span> {{ cc.email }}</div>
                                                <div class="info"><span>{% translate "Manzil:" %}</span> {{ cc.location }}</div>
                                            </div>
                                        </div>

                                    {% endfor %}
                                {% endif %}


                                <div class="text-center mt-5">
                                    <a href="#top" class="btn">{% translate "Наверх" %}</a>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </section>
    </section>


{% endblock %}


{% block js %}
    <script>
        $(document).ready(function () {
            if (window.location.search) {
                var urlParams = new URLSearchParams(window.location.search)
                id = urlParams.get('id')
                setTimeout(() => {$(`#nav-${id}-tab`).click()}, 1500)
            }
        });
    </script>
{% endblock %}

templates/magistr.html
{% extends 'base.html' %} {% load static %}{% load i18n %}
{% block title %}  {% endblock %}
{% block content %}
    {% for c in content %}
        <section class="section-science">
            <section class="section-content">
                <div class="container-xl">
                    <h2 class="title text-center">
                        {{ c.title }}
                    </h2>

                    <img src="{{ c.image.url }}" class="img-fluid w-100" alt="">

                    <h3 class="title2 text-center pt-5 mt-5 " style="color: black;">{{ c.title2 }}</h3>

                    <div class="content ">
                        {{ c.content | safe }}
                    </div>

                    <div class="text-center mt-5">
                        <a href="#top" class="btn">{% translate "Наверх" %}</a>
                    </div>

                </div>
            </section>
        </section>


    {% endfor %}
{% endblock %}

templates/new.html
{% extends 'base.html' %} {% load static %}{% load i18n %}
{% block title %} {{ c.title }} {% endblock %}
{% block content %}



    <section class="section-new">
        <section class="section-content">
            <div class="container-xl">
                <div class="text-center">
                    <img src="{{ c.image.url }}" class="img-fluid img w-100" alt="">
                </div>

                <a href="{% url 'news_category' c.new_id %}" style="font-size: 20px; color: #444444" class="text-left">{{ c.new }}</a>
                <h2 class="title text-left">
                    {{ c.title }}
                </h2>

                <p class="content">
                    {{ c.content | safe }}
                </p>


                <div class="text-center py-5 my-4">
                    <a href="{% url 'news' %}" class="btn">{% translate "К новости" %}</a>
                </div>


                <div class="row row-cols-1 row-cols-lg-3 news">
                    {% for new in category.new_set.all|slice:":3" %}
                        <div class="col new">
                            <img src="{{ new.image.url }}" class="img-fluid w-100" alt="">
                            <div class="title">{{ new.title }}</div>
                            <div class="descrip">{{ new.description }}</div>
                            <a href="{% url 'new' new.pk %}" class="link">{% translate "Подробнее о новости >" %}</a>
                        </div>
                    {% endfor %}
                </div>


            </div>
        </section>
    </section>




{% endblock %}

templates/news-category.html
{% extends 'base.html' %} {% load static %}{% load i18n %}
{% block title %} НОВОСТИ {% endblock %}
{% block content %}


    <section class="section-news-categoty">
        <section class="section-content">
            <div class="container-xl">
                <h2 class="title text-center">{% translate "НОВОСТИ" %}</h2>
                <div class="descr text-center">
                    {% translate "Самые последние новости нашего университета" %}
                </div>

                <div class="category">
                    <div class="cat-name">
                        {{ category.name }}
                    </div>
                    <div class="row row-cols-1 row-cols-lg-3 news">
                        {% for new in category.new_set.all %}

                            <div class="col new mb-5">
                                <img src="{{ new.image.url }}" class="img-fluid w-100" alt="">
                                <div class="title">{{ new.title }}</div>
                                <div class="descrip">{{ new.description }}</div>
                                <a href="{% url 'new' new.pk %}" class="link">{% translate "Подробнее о новости >" %}</a>
                            </div>

                        {% endfor %}

                    </div>
                </div>

                <div class="text-center  py-5">
                    <a href="{% url 'news' %}" class="btn">{% translate "К объявлениям" %}</a>
                </div>
            </div>
        </section>
    </section>

{% endblock %}